### ISSUE TITLE
Atmosphere evolution bug

### ISSUE THREAD

**Issue by icunnyngham** [ehpor/hcipy#129]
Aloha,

First of all, thank you for your wonderful work!  I have been using it for several years now for my research.  

It seems to me that a bug may have crept into the code for evolving atmospheres?  Very nonphysical looking ridges (i.e. vertical and horizontal lines) appear from the edges of the phase screen as I evolve a single layer atmosphere.  I could provide some boilerplate code if that would help?  It seems to happen independently of how granular my time-steps are.

I first noticed this late last year, but at the time suspected it had something to do with my switch in hardware (maybe the RNG in python for m1 hardware was somehow to blame?) but have now confirmed across a few platforms.

Is this something anyone else has noticed?  Thanks for any help!

**Comment by ehpor** [comment]
Do you have a picture? What PSD/parameters are you using? With Kolmogorov / large outer scales, there are some non-physical artefacts cropping up, but I don't think they looked like ridges.

**Comment by icunnyngham** [comment]
Sure, thanks!  This is for a 1024x1024 pupil-grid that is a bit over 2m on a side.  I believe I got the outer scale from an old tutorial, I don't know how realistic it is...

```cn2 = hcipy.Cn_squared_from_fried_parameter(.25, 550e-9)
atmos = hcipy.InfiniteAtmosphericLayer(
    tel.mas_psf_sampler.pupil_grid, 
    cn2, 
    200, # outer scale (nm)
    10,  # wind speed (m/s)
    100  # Height of single layer in meters, but may not be important for now
)
times = np.linspace(0, 1, 100)[1:]
# r0 = hcipy.atmosphere.seeing_to_fried_parameter(1.5, 600e-9)
# tel.generate_atmosphere(r0)
for t in times:
    atmos.t = t
    hcipy.imshow_field(atmos.phase_for(1))
    plt.colorbar()
    plt.title(f't = {t:.02f} s')
    plt.show()
```
![image](https://user-images.githubusercontent.com/1227773/182069955-abdb2dcf-3d80-4fff-8a8f-c059eb907488.png)

![image](https://user-images.githubusercontent.com/1227773/182069992-1944f50d-306b-4900-baa0-734914e33ce8.png)
![image](https://user-images.githubusercontent.com/1227773/182070023-ee0204a9-8df2-4d5d-a83a-770bccb2f77a.png)

**Comment by ehpor** [comment]
Ah, yeah, that's definitely instability inherent to the algorithm used to generate these phase screens. Doesn't seem like a bug in the M1 to me right now. I'll look a bit further in the morning.

Decreasing the outer scale always solves this (200m is on the large side), but might not be applicable to your atmosphere.

Increasing the `stencil_length` parameter can help too, but I personally haven't played around with that recently, so I don't have a better default parameter ready for you. Try increasing that from its default value of 2 to maybe 4 or 8, and see what that does.

**Comment by ehpor** [comment]
I wouldn't expect time granularity to have any effect here. Internally the phase screens are still evolved one column/row at a time, independent of the actual time step.

**Comment by icunnyngham** [comment]
Ah!!  Yes, reducing outer scale did indeed seem to improve the results a lot.   I will need to level up my knowledge of what constitutes realistic values for that.   Thank you!
