### ISSUE TITLE
Generating phase screens from MultiLayerAtmosphere? 

### ISSUE THREAD

**Issue by rmjc** [ehpor/hcipy#13]
Hello,

I've been successfully generating phase screens with:

layer = InfiniteAtmosphericLayer(...)
phase_screen = layer.phase_for(wavelength)

but it would be very useful to be able to generate phase screens from a MultiLayerAtmosphere as well. Is it possible to do this with the current version of the code?

**Comment by ehpor** [comment]
For reference, if anyone else has the same problem: use the `MultiLayerAtmosphere.phase_for(self, wavelength)` function, which returns the unwrapped phase of the atmospheric model. This function will not work if scintillation is turned on, as Fresnel propagation will wrap the phase, and calling it regardless will yield a `ValueError`. See a4ed54ab0f0d7d1a3f676591208ba60ba22565bd.
