### ISSUE TITLE
Add unit keyword for image display in imshow_field()

### ISSUE THREAD

**Issue by ivalaginja** [ehpor/hcipy#17]
Emiel and I talked about the option to scale the image display from `imshow_field()` by choice without having to manually scale the display grid. This would require to include a keyword that sets the grid scaling of the input image.

Iva:
> I realized that the HCIPy images are simply in units of radians [...] On the same note though, would it be of use to include a keyword in `imshow_field` that scales the images in lambda/D instead,  optionally? 

Emiel:
> [...] although it would be useful to have a
function for this, it shouldn't be automatic as you said (sometimes you
want to look at an image on a physical scale). Also most of the time I'm
using normalized coordinates anyway (ie. all my pupils have a diameter
of 1). In this case all the axes are already in lambda/D. If I use
physical units, and I want to see the image in physical coordinates I
always do something like:
`imshow_field(image, image.grid.scaled(1 / plate_scale))`
This will set the new grid (the second argument) before showing the new
Field. This is what I also use for on-sky data, letting me view the axes
both in arcsec, in mm on the detector, in pixels, or in lambda/D for
some wavelength. (Essentially I have a separate Grid for each case,
which are simply scaled versions of each other.) If you can find a good
way of automating this, I would be happy to merge/include that. I just
haven't found a way yet that is easier to remember than doing it
manually as above.

Iva:
>  It seems easy to just display your image in different units by redefining the grid as you show in your email, and I think the only way in which to make this more intuitive is to make a more "user friendly" input, which can be done in so many forms. One way would probably be to define a keyword which is used to feed in a scalar for exactly the kind of unit transformation like you do it on your grid when you scale it. Since all of them would be of the form 1/platescale on the grid of the input image to the plotting function, it would just take away the need for the user to redefine the grid, and they just provide the scaling factor (i.e. the wished for units). It would make it a tad easier to use, especially in cases where people don't use normalized pupils/wavelengths, and the way of doing it that you show does exactly what I've been thinking of. So I guess it would just be the matter of an extra keyword?

Emiel:
> I could live with a `grid_scaling_factor` parameter in `imshow_field()`, or something to that effect.

**Comment by ehpor** [comment]
I added this in 653226e64ca5892189803b7f5eb7cdd2e98436f9 with the name `grid_units`. It can be both a scalar and a two-dimensional array for different units in both axes.
