### ISSUE TITLE
'gaussian_mode' is not defined

### ISSUE THREAD

**Issue by sylacour** [ehpor/hcipy#191]
Looks like the mode basis 'gaussian_mode' is missing. Maybe it was removed? It is called by default in the SingleModeFiber Detector.

**Comment by ehpor** [comment]
I did a quick look through git history. It seems that this function got accidentally removed three years ago during a refactor. I'll work on this today, and fix some other issues with that part of the code base (it looks very outdated).

**Comment by syhaffert** [comment]
That part of the code base was developed early on when we wanted to do photometry with a single-mode fiber. This part of the code is almost never used. I actually think we might want to rethink the fiber detectors. I think they are a bit awkward to work with and they do not represent actual optical systems. It is probably better to replace them with an simplified single mode fiber optic and a normal detector class.

**Comment by syhaffert** [comment]
Btw @sylacour if you need to make a gaussian mode you can use newer code. We have implemented square and circular Gaussian mode basis (Guassian Hermite and Gaussian Laguerre) https://docs.hcipy.org/dev/api/hcipy.mode_basis.gaussian_hermite.html#hcipy.mode_basis.gaussian_hermite . The typical Gaussian mode is the fundamental mode for both basis sets. E.g. you could create it by using:

```
gaussian = hcipy.mode_basis.gaussian_hermite(0, 0, mode_field_diameter=mfd, grid=evaluation_grid)
```

**Comment by sylacour** [comment]
Thank you mentioning that. I will look into it.
For information, what I am trying to do is to simulate a dual field optical interferometer like GRAVITY. 
So I would use the singleMode fiber more like an optical element than a detector. I wasn’t really happy with the StepIndexFiber function as described in the tutorial.

**Comment by syhaffert** [comment]
So you want access to the complex mode coefficient of the Gaussian mode?

**Comment by ehpor** [comment]
@syhaffert 
> It is probably better to replace them with an simplified single mode fiber optic and a normal detector class.

I'm underway with exactly this. A pull request will appear soon (= today). The single mode fiber will be an optical element, with the outgoing wavefront just a complex amplitude.

**Comment by sylacour** [comment]
> So you want access to the complex mode coefficient of the Gaussian mode?
> 
Yes.

**Comment by ehpor** [comment]
As soon as #192 gets approved, you should be able to do something like:
```python
from hcipy import *
import numpy as np
import matplotlib.pyplot as plt

mode_field_diameter = 0.75  # mode field diameter of the fiber in units of your focal grid
fiber_position = [5, 0]  # position of the fiber in units of your focal grid

fiber_mode = make_gaussian_fiber_mode(mode_field_diameter)

pupil_grid = make_pupil_grid(512)
focal_grid = make_focal_grid(16, mode_field_diameter * 2).shifted(fiber_position)
prop = FraunhoferPropagator(pupil_grid, focal_grid)

aperture = make_circular_aperture(1)(pupil_grid)
wf = Wavefront(aperture)
wf.total_power = 1

smf = SingleModeFiberInjection(focal_grid, fiber_mode, fiber_position)

img = prop(wf)  # focal-plane wavefront
fiber_output = smf(img)
complex_amplitude = fiber_output.electric_field[0]
coupling_percentage = fiber_output.total_power * 100

plt.suptitle(f'{complex_amplitude=:.2g}; {coupling_percentage=:.2g}%')
plt.subplot(1,2,1)
plt.title('Input electric field')
imshow_field(img.electric_field)
plt.subplot(1,2,2)
plt.title('Fiber mode')
imshow_field(smf.mode)
plt.show()
```

Output:
![image](https://user-images.githubusercontent.com/38925765/235714946-06098bda-4ceb-4bab-8353-7140c61e5ea5.png)
