### ISSUE TITLE
addition hcipy 0.6.0 to Nixpkgs

### ISSUE THREAD

**Issue by NuggetOfficial** [ehpor/hcipy#232]
Hey!

I just wanted to let you know that hcipy 0.6.0 is awaiting approval to be added to Nixpkgs, which allows Nix user to easily install hcipy on nixOS. Please put a thumbs-up on the request as this will speed up the process. You can find the pull request here: https://github.com/NixOS/nixpkgs/pull/341906.

Cheers,
Tom

**Comment by ehpor** [comment]
I gave my thumbs up.
