### ISSUE TITLE
converting a field object to numpy array

### ISSUE THREAD

**Issue by AyanS13** [ehpor/hcipy#247]
Hi Hcipy team.

I use the hcipy package to generate Shack Hartmann spot patterns for a 6x6 lenslet array. I need to convert the field to a 2D numpy array for further computations. I tried looking at the source code, but I am confused about how the field elements will relate to a numpy array in 2D. 
Should I separate out along rows or columns?

Thanks a lot!

**Comment by ehpor** [comment]
You can use `spot_pattern.shaped` to reshape a field to an array. Note that this will still produce a `Field` object. To fully cast it to an array, you'd do something like:

```python
array = np.array(spot_pattern.shaped, copy=False)`
```

**Comment by AyanS13** [comment]
Thanks for the help!
