### ISSUE TITLE
Multiple spots on focal plane due to Franhoufer propagator?

### ISSUE THREAD

**Issue by AyanS13** [ehpor/hcipy#250]
Hi Hcipy team,
I have been using this package for quite a while to simulate various spot patterns for the Shack-Hartmann wavefront sensor. While doing that, I also generated the focal_grid and propagated the wavefront. But the problem is that the spots will increase if I reduce the number of pixels. Also, I noticed that the number of data points on the pupil plane and focal plane are different. Can this be kept the same in any way? Can you tell me why the number of spots increases when it should be just one?

I tried this on the Shack-Hartmann tutorial from the hcipy package, decreased the num_pixels, and got the following.

Thanks a lot
![output](https://github.com/user-attachments/assets/b0d10550-faff-4a3a-9cb3-a0f33b62bcda)

**Comment by ehpor** [comment]
Hi,

You are seeing "aliasing" of the Fourier transform that is used for the propagation from pupil to focal plane. This is fundamental math/physics and unavoidable: with N pixels across your pupil, you can only see up to N/2 lambda/D away. The point at N/2 lambda/D away is "Nyquist" and Fourier transforms will wrap/alias beyond that point.

The number of pixels in the focal plane does not matter, just the extent of it. In terms of parameters for the `make_focal_grid()`, it is the `num_airy` parameter that matters and cannot be larger than the number of pixels across your telescope pupil, not `q`, which is the number of pixels per lambda/D.

I hope that clarifies what you're seeing.

**Comment by AyanS13** [comment]
Yes, thanks a lot!
