### ISSUE TITLE
Regarding ShackHartmannWavefrontSensorEstimator.

### ISSUE THREAD

**Issue by AyanS13** [ehpor/hcipy#251]
While trying to simulate, a Shack Hartmann spot pattern, I tried to use the estimator function of the HCIPY package,
to calculate the slopes using `slopes_ref = shwfse.estimate([image_ref])`

I looked at the following function in the package:

```python
class ShackHartmannWavefrontSensorEstimator(WavefrontSensorEstimator):
    def __init__(self, mla_grid, mla_index, estimation_subapertures=None):
        self.mla_grid = mla_grid
        self.mla_index = mla_index
        if estimation_subapertures is None:
            self.estimation_subapertures = np.unique(self.mla_index)
        else:
            self.estimation_subapertures = np.flatnonzero(np.array(estimation_subapertures))
        self.estimation_grid = self.mla_grid.subset(estimation_subapertures)`

    def estimate(self, images):
        image = images[0]

        fluxes = ndimage.measurements.sum(image, self.mla_index, self.estimation_subapertures)
        sum_x = ndimage.measurements.sum(image * image.grid.x, self.mla_index, self.estimation_subapertures)
        sum_y = ndimage.measurements.sum(image * image.grid.y, self.mla_index, self.estimation_subapertures)

        centroid_x = sum_x / fluxes
        centroid_y = sum_y / fluxes

        centroids = np.array((centroid_x, centroid_y)) - np.array(self.mla_grid.points[self.estimation_subapertures, :]).T
        return Field(centroids, self.estimation_grid)
```

But I am not sure why it works? Shouldnt there be a division of the `centroids` array by the focal length of the lenslets?

**Comment by ehpor** [comment]
The implementation in HCIPy returns centroids in length units (whatever units your image grid were in, likely in meters). Yes, you can divide the centroids by the focal length to get the angles of each subaperture spot instead of the positional offset. 

However, for the purposes of AO, this is just a gain on each centroid (and the same gain for each centroid to boot). So, this can be absorbed by the reconstruction matrix.

In the end, this is just a subjective choice. You can divide the centroids by the focal length if that's easier for your application.

**Comment by AyanS13** [comment]
Thanks for the clarification. 

I am trying to calculate the auto-correlation function for slopes across different pairs of lenslets to profile atmospheric turbulence. Now the problem I am facing is that the auto-correlation function values I am getting after dividing out focal length are nowhere close to the theoretical rms tilt that one should get for a value of r0.

For example, at `lambda = 550 nm` if `r0 = 0.075m`, then `rms_tilt = 0.7''`. This gave me an estimate that the wavefront slope_auto-correlations should be somewhere between`~ 0.4 - 0.7 (arcsec^2)`. 

Now if I use the `slopes = shwfse.estimate([image])` for calculating my slope, the auto-correlation values come out to be very close to what is expected. 
![r0_0 05_10fr](https://github.com/user-attachments/assets/fde95d5f-bf3e-4fce-947e-5c0875872b48)

The issue is that the y-axis should not be `arcsec^2` if the focal length is not divided out of the centroid shift. But still, it is matching closely. I have tried using the same with multiple different values of `r0` and running the simulation for at least 10 frames, and they are consistent with the `rms_tilt`.
If I divide by the focal length and then calculate the auto-correlation, the values come out way too higher than expected,`>1000 arcsec^2`.

I am not sure what is happening here. I would greatly appreciate some insight into this problem.

**Comment by ehpor** [comment]
If you have some example code that calculates the >1000 number, I can take a look.

**Comment by AyanS13** [comment]
Yes, I do; because it's a long code, I am attaching the Github repository link for it. Thanks for the help!![code](https://github.com/AyanS13/SLODAR-using-hcipy/blob/main/re_Ayan_SLODAR.ipynb)

**Comment by AyanS13** [comment]
I am sorry. I have made it public right now.

**Comment by ehpor** [comment]
The expected angle autocorrelation values are for angles on the sky, not angles at the WFS pupil. You need to correct the angles for the magnification from the telescope pupil to the SHWFS pupil.

**Comment by AyanS13** [comment]
Alright! I missed that. So, I basically should divide the slope (`del_x / f_lenslet`) I have previously got by the scaling factor, which is the magnification `(telescope_pupil/SHWFS_pupil)`?
