### ISSUE TITLE
scipy.misc.imsave has been deprecated and removed in scipy v1.2.0

### ISSUE THREAD

**Issue by jamienoss** [ehpor/hcipy#40]
https://docs.scipy.org/doc/scipy-1.2.0/reference/generated/scipy.misc.imsave.html

**Comment by ehpor** [comment]
As far as I can see, we switched to `imageio.imwrite()` in 92a646acdb1cec6d197aadd2857d9ada96b51dea and 95dc7a661a4ddd0725def2a2ebf55e2024414c4d. Both commits are in the 0.2 release. Did I miss any?

**Comment by jamienoss** [comment]
Sorry, you are totally correct. Now that I've slept and had some coffee, I've discovered the culprit, which is that you and Remi copied the entire hcipy repo into our stroke-min folder on HiCAT and it obviously hasn't been updated. I had forgotten about this and wasn't paying close enough attention to the backtrace path for hcipy before throwing this over the fence at you.
