### ISSUE TITLE
Unpin coverage version

### ISSUE THREAD

**Issue by ehpor** [ehpor/hcipy#46]
Due to an update of coverage on December 14 to version 5.0, the coveralls module is broken. coverage<5.0 was pinned in 7bf2215aa1345e84976f33a11fefd40a30de3e06. This will be removed when coveralls-clients/coveralls-python#203 gets addressed.

**Comment by TheKevJames** [comment]
I've just released `coveralls==1.10.0` with support for the latest `coverage`; this should now be unblocked.

**Comment by ehpor** [comment]
Thanks for notifying me. Everything seems good now. Thanks for your work.
