### ISSUE TITLE
Resolve compatibility with Scipy 1.2

### ISSUE THREAD

**Issue by chen-pin** [ehpor/hcipy#50]
Scipy deprecated `imsave` and removed it from ver. 1.2.0.  Thereby, an `imsave` import statement in HCIPy prevents it from running in environments w/ scipy 1.2.0 or higher.

**Comment by ehpor** [comment]
What version are you using? It should be fixed in 0.2, released last August, which is on PyPI. See issues #40 and #25. Also see commits 92a646acdb1cec6d197aadd2857d9ada96b51dea and 95dc7a661a4ddd0725def2a2ebf55e2024414c4d.

**Comment by chen-pin** [comment]
Thank you!  I am using an older version.  My bad.

**Comment by ehpor** [comment]
No problem. FYI: HCIPy 0.3 will be out in a few days and implements, among other things, full Stokes propagation through vector vortex coronagraphs.

**Comment by chen-pin** [comment]
That's great news. Thanks! Pin 

Sent from Yahoo Mail on Android 
 
  On Sun, Jan 5, 2020 at 10:27 PM, Emiel H. Por<notifications@github.com> wrote:   
No problem. FYI: HCIPy 0.3 will be out in a few days and implements, among other things, full Stokes propagation through vector vortex coronagraphs.

**Comment by chen-pin** [comment]
Dear Dr. Por,

I have a code-compatibility issue with HCIPY v0.2, but not with a prior release.  Any advice you can give would be much appreciated.  I defined an `OpticalElement` as follows:  

--CODE SNIPPET--
class FresnelBack(hci.OpticalElement):
        def __init__(self, input_grid, distance, wavelength=1):
        self.input_grid = input_grid
        self.distance = distance
        self.wavelength = wavelength
        self.prop = hci.FresnelPropagator(input_grid=self.input_grid
                                         , distance=self.distance)
    def forward(self, wavefront):
        return self.prop.backward(wavefront)
    def backward(self, wavefront):
        return self.prop.forward(wavefront)-----
When I run the forward propagation using the latest HCIPY, I get the following error:
--ERROR MESSAGE--RuntimeError: Output grid is not known. Perform a forward propagation first before backwards propagation on the same grid.-----
Performing a forward propagation first (as the error message suggests) gets over this error, but it causes problems elsewhere in my code.  Also, it seems inefficient to do an extra propagation ...  Is there anyway I can pass in the output grid without having to run a forward propagation first?  

Using HCIPY's built-in `FresnelPropagator` and running .backward() throws the same error.  

FYI, the code runs fine with an older HCIPY release.  

Thank you very much in advance!
Pin


    On Monday, January 6, 2020, 12:27:28 AM PST, Emiel H. Por <notifications@github.com> wrote:  
 
 
No problem. FYI: HCIPy 0.3 will be out in a few days and implements, among other things, full Stokes propagation through vector vortex coronagraphs.

**Comment by syhaffert** [comment]
Hi Pin,

You could bypass this issue by doing a forward propagation with a negative distance. A negative distance forward propagation behaves in the same way as a position distance backward propagation. But the behavior that you mentioned definitely deserves its own discussion in the future as I have had this issue several times too now.

**Comment by chen-pin** [comment]
Hi Sebastiaan,Thank you so much for your prompt response!  I'll try your suggestion. 
Pin

    On Wednesday, January 22, 2020, 10:57:53 AM PST, Sebastiaan Haffert <notifications@github.com> wrote:  
 
 
Hi Pin,

You could bypass this issue by doing a forward propagation with a negative distance. A negative distance forward propagation behaves in the same way as a position distance backward propagation. But the behavior that you mentioned definitely deserves its own discussion in the future as I have had this issue several times too now.

**Comment by ehpor** [comment]
With HCIPy 0.2 you can indeed bypass by having a negative distance. However, in HCIPy 0.3.0, out since yesterday, there are should be no problems doing a backward() propagation right away, as part of a renewed way of handling caching in optical elements.

**Comment by chen-pin** [comment]
Thank you!  -Pin

    On Wednesday, January 22, 2020, 11:27:13 AM PST, Emiel H. Por <notifications@github.com> wrote:  
 
 
With HCIPy 0.2 you can indeed bypass by having a negative distance. However, in HCIPy 0.3.0, out since yesterday, there are should be no problems doing a backward() propagation right away, as part of a renewed way of handling caching in optical elements.

**Comment by chen-pin** [comment]
Hi Emiel,
If I may trouble you again ... I upgraded to HCIPY v0.3.0 and ran my code.  This indeed took care of the error I mentioned before.  However, I now get another error with the following traceback:  

--EXCERPT FROM ERROR MESSAGE--
  File "/home/pinchen/sleec/source/sleec_optics.py", line 159, in forward
    return self.prop.backward(wavefront)
  File "/home/pinchen/anaconda3/lib/python3.7/site-packages/hcipy/optics/optical_element.py", line 761, in res
    instance_data = self.get_instance_data(None, wavefront.grid, wavefront.wavelength)
  File "/home/pinchen/anaconda3/lib/python3.7/site-packages/hcipy/optics/optical_element.py", line 633, in get_instance_data
    self.make_instance(instance_data, input_grid, output_grid, wavelength)
  File "/home/pinchen/anaconda3/lib/python3.7/site-packages/hcipy/propagation/fraunhofer.py", line 38, in make_instance
    instance_data.fourier_transform = make_fourier_transform(input_grid, instance_data.uv_grid)
  File "/home/pinchen/anaconda3/lib/python3.7/site-packages/hcipy/fourier/fourier_transform.py", line 162, in make_fourier_transform
    if input_grid.is_separated and input_grid.is_('cartesian') and output_grid.is_separated and output_grid.is_('cartesian') and input_grid.ndim in [1,2]:
AttributeError: 'function' object has no attribute 'is_separated'-----
Any advice would be much appreciated!
Best, 
Pin



    On Wednesday, January 22, 2020, 11:27:13 AM PST, Emiel H. Por <notifications@github.com> wrote:  
 
 
With HCIPy 0.2 you can indeed bypass by having a negative distance. However, in HCIPy 0.3.0, out since yesterday, there are should be no problems doing a backward() propagation right away, as part of a renewed way of handling caching in optical elements.

**Comment by ehpor** [comment]
Yes, that's an actual bug. Let's continue the conversation in #55.
