### ISSUE TITLE
FFMpegWriter error on Mac 

### ISSUE THREAD

**Issue by spbos** [ehpor/hcipy#59]
When generating movies on a Mac using the FFMpegWriter the code crashes. The codec is set to 'mpeg4', which should work on a Mac. But the following error occurs:

movie.add_frame(fig=fig)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/hcipy/plotting/animation.py", line 255, in add_frame
    fig.savefig(self.p.stdin, format='png', transparent=False, dpi=dpi)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 532, in print_png
    self.figure.dpi, metadata=metadata)
SystemError: <built-in method write of _io.BufferedWriter object at 0x11a34feb8> returned a result with an error set

**Comment by ehpor** [comment]
Can you add a minimal working example?

**Comment by spbos** [comment]
Sorry for my late response. Here is the example:

import numpy as np 
import matplotlib.pyplot as plt 

from hcipy import * 

N = 32

grid = make_pupil_grid(N)

movie = FFMpegWriter('test.mp4', framerate=10, quality=None, preset=None)

for i in np.arange(10):

    test = Field(np.random.rand(N**2), grid)

    fig = plt.figure()
    imshow_field(test)

    movie.add_frame(fig=fig)

    plt.close()

movie.close()

**Comment by spbos** [comment]
This generates a movie, which I subsequently cannot open on Mac

**Comment by ehpor** [comment]
I pushed a potential fix to the `ffmpeg_for_mac` branch, following https://trac.ffmpeg.org/wiki/Encode/H.264#QuickTime.

I don't have a Mac to test this. @spbos can you check if the video generated by the minimal working example above now plays correctly?

**Comment by spbos** [comment]
When explicitly setting the codec to 'mpeg4' it works, otherwise it doesn't work.

**Comment by ehpor** [comment]
Some more clarification:
* the errors in the original post above were not reproduced with the current master branch. No exceptions are thrown for all use cases. It's just that the video file cannot be played for some cases.
* codec mpeg4 works both in the `master` branch and in the `ffmpeg_for_mac` branch.
* codec libx264 doesn't work both in the `master` branch and in the `ffmpeg_for_mac` branch.
* The generated video file for libx264 on Mac can run in Linux.

**Comment by ehpor** [comment]
I may have found the problem. I was ordering the arguments for the call to ffmpeg wrong. Therefore, I thought I set the correct pixel format, while in actuality I made no changes at all. The default pixel format is now yuv420p instead of yuv444p, so generated mp4 videos now should also play on Mac.

I double checked the pixel format with:
`ffprobe -select_streams v -show_streams test.mp4`

@spbos Can you check again?

**Comment by ehpor** [comment]
We confirmed that this now solves the problem.
