### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'float' and 'CartesianGrid'

### ISSUE THREAD

**Issue by WarheadTR** [ehpor/hcipy#60]
Hello,

I installed the hcipy library to use on windows 10 (x64). I wanted to run "II - Wavefronts and optical systems" by writing it from scratch. However, there is an error in the python terminal.

**"TypeError: unsupported operand type (s) for /: 'float' and 'CartesianGrid'"**

The file that is the source of this error is "\ hcipy \ field \ util.py"

My python version:
Python 3.8.1 (tags / v3.8.1: 1b293b6, Dec 18 2019, 23:11:46)

Here is full error:

> Traceback (most recent call last):
  File "C:/Users/RECEP/OneDrive/Python/PycharmProjects/WORKBENCH/dag_ao.py", line 10, in <module>
    focal_grid = make_focal_grid(pupil_grid, 8, 16)
  File "C:\Users\RECEP\AppData\Local\Programs\Python\Python38\lib\site-packages\hcipy\field\util.py", line 187, in make_focal_grid
    delta = float(spatial_resolution) / q * np.ones(2)
TypeError: unsupported operand type(s) for /: 'float' and 'CartesianGrid'
>

**Comment by syhaffert** [comment]
When the initial documentation was written there was a slightly different interface for the make_focal_grid function. It seems like the documentation was not updated when the new interface was created. The current interface is
`focal_grid = make_focal_grid(q, num_airy, spatial_resolution)`
For the intro II it should be:
`focal_grid = make_focal_grid(q=8, num_airy=16, spatial_resolution=1)`
This should fix your issues.

**Comment by WarheadTR** [comment]
Thank you, syhaffert. It works.

**Comment by ehpor** [comment]
I added a less obtuse error message for this type of error in 4fac39fa4112ca64de15e0f5f6b6466cf41c5f42. I also fixed the documentation that used the old signature in 627a5e0c852471e8a1c08b24f58ebc475ffe8039.
