### ISSUE TITLE
Would you please add some examples of laser propagating throungh a lens?

### ISSUE THREAD

**Issue by fbl1991** [ehpor/hcipy#73]
Thanks for this specially designed wonderful light propagation simulation code. After carefully studying for a while, I want to do some simulations. However I am not sure how to do some common simultions, such as laser propagation through a lens. I think many others would have such kind of confusion, too. Would you please spare some time to add some examples? That must be very kind and patient of you.

**Comment by syhaffert** [comment]
What kind of system would you like to see?Laser propagation through a lens can mean quite a lot of things.

Do you mean a Fraunhofer propagation for a gaussian beam? In this case the first tutorial "Making a broadband telescope point spread function" is suitable where the only difference would be changing the wavefront's electric field from a clear aperture to a gaussian shape. You can create a Gaussian beam like this:

`gb = GaussianBeam(waist_radius, 0, wavelength)
wf = gb.evaluate(grid)`

Or do you mean a Fresnel propagation with a perfect thin lens? We indeed do not have tutorials yet of such a Fresnel propagation.

**Comment by fbl1991** [comment]
Thank you for this replay. I want to start with a gaussian beam propagating through a perfect lens with focal length of L. Which parts do you add the phase distortation effect of such a lens in your code? In the 'wavefront' or 'make_focal_grid' or 'FraunhoferPropagator'? I think this is one the most elegant  design in your code, but it really makes me confused. Would you explain it more detailly? Thank you so much.

**Comment by syhaffert** [comment]
As yes that is possible through Fresnel propagation. Sadly we do not have a tutorial/example of that yet. But we have implemented something similar in the ShackHartmannWavefrontSensor optical element. There we take a wavefront apply a microlens opd profile and fresnel propgate to the focus. This is similar to what you want to do except you should switch out the microlens surface with a thin lens surface. You can see a short example below, here I propagate a certain distance to the front focal plane and then apply a propagation to the lens surface, apply the lens and propagate to the focus.

```
wf = Wavefront(electric_field, wavelength)

prop1 = FresnelPropagator(input_grid, distance_to_front_focal_plane)
prop2 = FresnelPropagator(input_grid, focal_length)

opd = (-1 / (2 * focal_length)) * input_grid.as_('polar').r**2
refractive_index = 1.5
thinlens = SurfaceApodizer(opd, refractive_index)

wf_ffp = prop1.forward(wf)
wf_at_lens = prop2.forward(wf_ffp)
wf_after_lens = thinlens.forward(wf_at_lens)
wf_focus = prop2.forward(wf_after_lens)
```

**Comment by fbl1991** [comment]
Thank your very much. That's very nice of you.

**Comment by syhaffert** [comment]
Have you been able to get a working simulation? If yes then we can close this issue.
