### ISSUE TITLE
NoisyDetector enhancement: subsample field 

### ISSUE THREAD

**Issue by spbos** [ehpor/hcipy#75]
Currently, when trying to integrate supersampled Wavefronts with the Noisy Detector, you first have to manually subsample the electric field to the correct grid size of the detector. I find this a bit cumbersome and unnecessary. 

I think it would be more intuitive (and convenient) if we add the subsampling also to the integrate function of the Noisy Detector. The code would check if the wavefront grid shape matches the grid shape of the detector. Then, if necessary, it would subsample it to the correct shape. 

@ehpor If you like this idea, I can code it up and create a new pull request this week.

**Comment by ehpor** [comment]
Agreed. But I wouldn't make it adaptive: that may be unpredictable when you change sampling. Put in the amount of oversampling in the `__init__()`, and let the `integrate()` function do the subsampling always by this factor. That would be cleaner, I think. Go for it!

**Comment by spbos** [comment]
Submitted a pull request.
