### ISSUE TITLE
NoisyDetector with photon noise is all photon noise!

### ISSUE THREAD

**Issue by icunnyngham** [ehpor/hcipy#77]
https://github.com/ehpor/hcipy/blob/3a5fe3a862d8247ad57adfeec3300bd1b884df41/hcipy/optics/detector.py#L190

I believe this line should be += rather than = .  As it is, the NoisyDetector with photon noise enabled just returns photon noise!

Aloha and thanks,
~Ian Cunnyngham

Edit: I guess I wasn't understanding how large_poisson worked, so this line is fine.  Still scratching my head as to why my attempt to use NoisyDetector ends up with just photon noise

**Comment by ehpor** [comment]
You need to set the `wavefront.total_power` at the number of incoming photons per second. The default is around 0.75 (depends on the area of your telescope pupil) so the image will be very noisy indeed if you don't change it yourself. If that doesn't solve your problem, let me know.

**Comment by icunnyngham** [comment]
Thank you so much for the response!  Sorry I didn't follow up right away, life has been crazy!  What are the units of this?  If W/m^2 than .75 is quite large indeed!
Mahalo plenty,
~Ian

**Comment by ehpor** [comment]
It's in photons per second.

(Or in photons per time unit, where the time unit can be whatever you want to use, as long as you use that unit consistently everywhere else as well. But I think most people just use seconds as the time unit.)

**Comment by icunnyngham** [comment]
Okay, thank you so much, the results look reasonable now.  Are the read_noise and flat_noise set in photons/sec rates as well?
