### ISSUE TITLE
Numpy AttributeError

### ISSUE THREAD

**Issue by rbalbay** [ehpor/hcipy#90]
Hello dear developers.
I am getting this error. I am guessing this error happening with newest scipy and numpy versions. 
After I install python 3.9 (x64) then numpy (1.18.5 - also I tried with 1.19.4) and scipy (1.4.1 - also I tried 1.5.4).
My code was running older versions but now some part (atmosphere I guess) is now working.

Maybe in requirments file you should specify which versions what you develepod. (just idea)

Here is my code: 

`
cn2 = [[9.57, 9, 649], [10.83, 9, 1299], [4.37, 15, 2598], [6.58, 25, 5196], [3.71, 40, 10392], [6.71, 21, 20785]]

cn_squared = Cn_squared_from_fried_parameter(r0, 500e-9)

atm_layers = []

for i in cn2:
    layer = InfiniteAtmosphericLayer(pupil_grid, i[0], L0, i[1], i[2])
    atm_layers.append(layer)

atmosphere = MultiLayerAtmosphere(layers=atm_layers)

atmosphere.Cn_squared = cn_squared

atmosphere.reset()

atmosphere.evolve_until(1)
`

Error:

Traceback (most recent call last):
  File "..\PycharmProjects\AO\dag_ao.py", line 165, in <module>
    imshow_field(atmosphere.phase_for(wavelength), cmap='RdBu')
  File "C:\Users\rbalb\AppData\Local\Programs\Python\Python39\lib\site-packages\hcipy\plotting\field.py", line 75, in imshow_field
    grid = field.grid
AttributeError: 'numpy.ndarray' object has no attribute 'grid'

**Comment by ehpor** [comment]
What version of HCIPy are you running? This error feels similar to one I had half a year ago, fixed in fffd3ba6b9f33276b900d5fd6e35dd04c9357514, though this might be a new one.

**Comment by rbalbay** [comment]
Here is my modules versions:

- numpy : 1.18.5 (also 1.19+ versions doesn't works)
- scipy : 1.5.4
- matplotlib : 3.3.3
- Pillow : 8.0.1
- pyyaml : 5.3.1
- astropy : 4.2
- imageio : 2.9.0
- xxhash : 2.0.0
- numexpr : 2.7.1
- asdf : 2.7.1

Python 3.9 (x64)

**Comment by ehpor** [comment]
And your *HCIPy* version? You installed the latest pip version or the development version? The commit I mentioned is not in the 0.3.1 while it is in the master branch of the development version.

**Comment by rbalbay** [comment]
HCIPy : 0.3.1
pip: 20.3.1

**Comment by rbalbay** [comment]
I have installed python 3.9 & pycharm 2020.3. 
Then updated setuptools & pip in pycharm.
Then I installed depencies (numpy, scipy etc.) with pycharm. 
After all, I installed HCIPy with pycharm.

**Comment by ehpor** [comment]
Then I'm convinced that this bug has already been fixed by fffd3ba6b9f33276b900d5fd6e35dd04c9357514.

* Super quick fix: supply a field to the `imshow_field()` function directly: `imshow_field(atmosphere.phase_for(wavelength), pupil_grid, cmap='RdBu')`.
* Quick but slightly slower fix: install the latest development version of HCIPy instead. (Not preferred if you want reproducibility for publication.)
* Slowest but best fix: wait for the 0.4.0 release, which is soon. I wanted to release this earlier, but finishing my thesis, SPIE proceeding, moving and PhD defense took/take precedence.

**Comment by rbalbay** [comment]
Now I tried : imshow_field(atmosphere.phase_for(wavelength), pupil_grid, cmap='RdBu') and it works. 

Thank you. My best regards

**Comment by ehpor** [comment]
Just to be completely sure that it's not something new, as that's not 100% clear to me yet. By *"installed HCIPy with pycharm"* you mean you did:

```
pip install hcipy --upgrade
```

instead of 

```
git clone https://github.com/ehpor/hcipy
cd hcipy
pip install -e .
```

Or is *"installed with pycharm"* a way of package installation that I'm completely unaware of.

**Comment by rbalbay** [comment]
I am using pycharm and I guess pycharm did this:

**pip install hcipy** 

Beceause I didn't git clone.

**Comment by ehpor** [comment]
Perfect. Then I'll close this.
