### ISSUE TITLE
Scaling of phase_dot_diameter for the ZernikeWavefrontSensor

### ISSUE THREAD

**Issue by yinzi-xin** [ehpor/hcipy#93]
On line 42 of zernike_wavefront_sensor.py, the phase_dot_diameter gets divided by lambda/D, but it should get multiplied by lambda/D, I think.

Edit: there might be something else going on, but at least in my personal simulation it seems to work with it flipped. To be investigated further.

@dsdoelman

**Comment by syhaffert** [comment]
There is indeed a mistake in the interface of the Zernike class. The current implementation assumes that the phase dot diameter has a physical size. But the documentation says the size should be given in units of lambda/D. I have fixed this bug in my current working branch.

The temporary fix until I have merged the new branch is to give the phase dot diameter in physical units.

**Comment by ehpor** [comment]
I'd like to get this merged sooner. I'll make a separate PR for this right now. A PR should only address a single thing, not a whole slew of fixes @syhaffert.
